language: node_js

sudo: required

node_js:
  - 13

cache: npm

before_install:
  - npm install -g ganache-cli truffle@5.1

install:
  - cd app
  - npm install 
  - cd ..

script:
  - ganache-cli --quiet &
  - truffle test
  - truffle compile
  - truffle migrate --reset
  - cd app
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: app/dist
  keep_history: true
  on: 
    branch: master
